language: cpp
os: linux
dist: trusty
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
          packages:
            - qtbase5-dbg qtbase5-dev qtbase5-dev-tools
            - valgrind
            - g++
            - doxygen
      env:
        - QMAKESPEC=linux-g++
        - EVAL="CC=gcc && CXX=g++"
        - CFLAGS="-Os"
        - LDFLAGS="-Wl,--no-undefined -lm"
        - QMAKEFLAGS="-config release"
install:
script:
  - PATH=`echo /opt/qt*/bin`:$PATH
  - eval "$EVAL"
  - make -s -f Makefile.configure configure | tee .config
  - make -k
        CFLAGS="$CFLAGS -march=native -g1 -Wall -Wextra -Werror"
        CPPFLAGS="-DNDEBUG"
        lib/libtinycbor.a
  - size lib/libtinycbor.a | tee sizes
  - make -s clean
  - make -k
        CFLAGS="$CFLAGS -O0 -g"
        LDFLAGS="$LDFLAGS" ${LDLIBS+LDLIBS="$LDLIBS"}
  - grep -q freestanding-pass .config || make
        QMAKEFLAGS="$QMAKEFLAGS QMAKE_CXX=$CXX"
        tests/Makefile
  - grep -q freestanding-pass .config ||
        (cd tests && make check -k
        TESTRUNNER=`which valgrind 2>/dev/null`)>/dev/null
  - make -s clean
  - #./scripts/update-docs.sh
